data:
  - attributes:
      created_at: '2024-04-10T21:58:17'
      destination_override_endpoint: 'https://bobham-774de8219399.herokuapp.com'
      entries:
        - classifiers: {}
          config:
            condition: AND
            expression: null
            rules:
              - condition: null
                expression:
                  field: Method
                  operator: equals
                  type: string
                  values:
                    - POST
                rules: null
          id: eb1dc395-f799-441f-bbea-737530d510d7
          id_selector: null
          operation: REDACT
          operations: null
          phase: REQUEST
          public_token_generator: UUID
          targets:
            - body
          token_manager: PERSISTENT
          transformer: JSON_PATH
          transformer_config:
            - $.card_number
            - $.card_cvc
          transformer_config_map: null
        - classifiers: {}
          config:
            condition: AND
            expression: null
            rules:
              - condition: null
                expression:
                  field: Method
                  operator: equals
                  type: string
                  values:
                    - POST
                rules: null
          id: db4789d0-d0c3-49c8-905d-89cbdc8be890
          id_selector: null
          operation: ENRICH
          operations: null
          phase: REQUEST
          public_token_generator: UUID
          targets:
            - body
          token_manager: PERSISTENT
          transformer: JSON_PATH
          transformer_config:
            - $.card_holder
            - $.card_exp
          transformer_config_map: null
      host_endpoint: (.*)\.verygoodproxy\.com
      id: 4c75d2bb-efdb-434d-b429-3f1829fca980
      ordinal: null
      port: 80
      protocol: http
      source_endpoint: '*'
      tags:
        name: bobs hamburger - inbound route
        source: Inbound Guide
      updated_at: '2024-04-15T17:20:27'
    id: 4c75d2bb-efdb-434d-b429-3f1829fca980
    type: rule_chain
  - attributes:
      created_at: '2024-04-11T22:32:31'
      destination_override_endpoint: '*'
      entries:
        - classifiers: {}
          config:
            condition: AND
            expression: null
            rules:
              - condition: null
                expression:
                  field: PathInfo
                  operator: matches
                  type: string
                  values:
                    - (.*)
                rules: null
          id: f2f21869-a42b-4b08-8356-e842b1d68bab
          id_selector: null
          operation: ENRICH
          operations: null
          phase: REQUEST
          public_token_generator: UUID
          targets:
            - body
          token_manager: PERSISTENT
          transformer: FORM_FIELD
          transformer_config:
            - 'card[number]'
            - 'card[cvc]'
          transformer_config_map: null
      host_endpoint: api\.stripe\.com
      id: 16003095-c2fd-4efd-ae56-d9a131e74992
      ordinal: null
      port: 80
      protocol: http
      source_endpoint: '*'
      tags:
        integration: stripe--formData
        name: bobs hamburger - outbound route (stripe)
        source: IntegrationTemplates
      updated_at: '2024-04-14T20:45:56'
    id: 16003095-c2fd-4efd-ae56-d9a131e74992
    type: rule_chain
  - attributes:
      created_at: '2024-04-15T01:11:44'
      destination_override_endpoint: '*'
      entries:
        - classifiers: {}
          config:
            condition: AND
            expression: null
            rules:
              - condition: null
                expression:
                  field: PathInfo
                  operator: matches
                  type: string
                  values:
                    - /post
                rules: null
              - condition: null
                expression:
                  field: ContentType
                  operator: equals
                  type: string
                  values:
                    - application/json
                rules: null
          id: 4dc75ab4-dada-4226-9f5c-a62db9d47cd4
          id_selector: null
          operation: ENRICH
          operations: null
          phase: REQUEST
          public_token_generator: UUID
          targets:
            - body
          token_manager: PERSISTENT
          transformer: JSON_PATH
          transformer_config:
            - $.card_number
            - $.card_cvc
          transformer_config_map: null
      host_endpoint: 484c-46-240-182-227.ngrok-free.app
      id: 1b5fc732-be23-44d1-b6ea-64410de3cdc4
      ordinal: null
      port: 80
      protocol: http
      source_endpoint: '*'
      tags:
        name: bobs hamburger - outbound route (local server test)
        source: RouteContainer
      updated_at: '2024-04-15T13:50:07'
    id: 1b5fc732-be23-44d1-b6ea-64410de3cdc4
    type: rule_chain
version: 1
